image: atlassian/default-image:2.13

pipelines:
  branches:
    main:
      - step:
          name: Production Build
          deployment: main
          script:
            - zip -r hiso.zip *
          artifacts:
            - hiso.zip
      - step:
          name: Upload to S3
          services:
            - docker
          script:
            - pipe: atlassian/aws-code-deploy:0.2.3
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                COMMAND: 'upload'
                S3_BUCKET: $AWS_BUCKET_TARGET
                APPLICATION_NAME: $APPLICATION_NAME
                ZIP_FILE: 'hiso.zip'
      - step:
          name: Deploy with CodeDeploy
          services:
            - docker
          script:
          # Test upload
            - pipe: atlassian/aws-code-deploy:0.2.3
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                COMMAND: 'deploy'
                S3_BUCKET: $AWS_BUCKET_TARGET
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
                WAIT: 'true'
                DEBUG: 'true'